server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  # eureka 服务端的实例名字
  client:
    # 表示不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/
      # 集群指向其他 eureka, 单机就是自己
      defaultZone: http://eureka7001.com:7001/eureka/
#  server:
    # 关闭自我保护机制，保证不可用服务及时剔除
#    enable-self-preservation: false   # 测试Eureka 非保护模式配置
#    eviction-interval-timer-in-ms: 2000


